CREATE DATABASE takalo;

USE takalo;

-- TABLE ROLE
CREATE TABLE ROLE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL
);

--TABLE UTILISATEUR
CREATE TABLE UTILISATEUR(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    role_id INT,
    FOREIGN KEY (role_id) REFERENCES ROLE(id)
);






